### ISSUE TITLE
Feature request: Only save page if there is no snapshot yet

### ISSUE THREAD

**Issue by baerbock** [palewire/savepagenow#14]
My usecase of your **great tool** is to archive articles before they've vanished behind a paywall.

Because I don't want to stretch the Internet Archive's resources without real necessity I would like to only save a page if there is no snapshot yet.

What do you think about implementing this?

**Comment by palewire** [comment]
How would such a test be accomplished?

**Comment by baerbock** [comment]
There is an API called `http://archive.org/wayback/available?url=$url`

Here are example results:
* [positive](https://archive.org/wayback/available?url=https://rbnenergy.com/shes-electric-are-e-fracs-a-fix-for-permian-gas-constraints-and-giveaway-prices)

`{"url": "https://rbnenergy.com/shes-electric-are-e-fracs-a-fix-for-permian-gas-constraints-and-giveaway-prices", "archived_snapshots": {"closest": {"status": "200", "available": true, "url": "http://web.archive.org/web/20190713192002/https://rbnenergy.com/shes-electric-are-e-fracs-a-fix-for-permian-gas-constraints-and-giveaway-prices", "timestamp": "20190713192002"}}}`

* [negative](https://archive.org/wayback/available?url=https://www.youporn.com/watch/14871319/sislovesme-foot-play-with-my-stepsis/)

`{"url": "....", "archived_snapshots": {}}`

**Comment by chazanov** [comment]
@palewire I'd like to implement this feature, but I'm a Python beginner. Do you think it can be easily done?

**Comment by victoriatomzik** [comment]
@chazanov we need it, go for it!

**Comment by palewire** [comment]
Sounds like it would be a great add.

**Comment by palewire** [comment]
I'll take any pull requests you might have for this, but I'm closing the ticket so it's gotten a bit stale.
