### ISSUE TITLE
Unable to save url after recent Wayback changes

### ISSUE THREAD

**Issue by pyprism** [palewire/savepagenow#27]
I already updated the library to version to 1.0.1 , still I am unable to save urls . Here is the codes :

```
def save_wayback(main_url):
    try:
        wayback = savepagenow.capture_or_cache(main_url)
        wayback_url = wayback[0]
        archived = True
        error = None
    except Exception as e:
        wayback_url = ''
        archived = False
        error = str(e)
    return wayback_url, archived, error
```

error message: 
`{'Server': 'nginx/1.15.8', 'Date': 'Fri, 17 Jul 2020 12:24:19 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '178', 'Connection': 'keep-alive', 'X-App-Server': 'wwwb-app103', 'X-ts': '520'}`

and sample url : [Link](https://tbsnews.net/bangla/%E0%A6%AC%E0%A6%BE%E0%A6%82%E0%A6%B2%E0%A6%BE%E0%A6%A6%E0%A7%87%E0%A6%B6/%E2%80%98%E0%A6%AB%E0%A6%BE%E0%A6%B9%E0%A6%BF%E0%A6%AE%E0%A7%87%E0%A6%B0-%E0%A6%B8%E0%A6%A6%E0%A6%BE-%E0%A6%B9%E0%A6%BE%E0%A6%B8%E0%A6%BF%E0%A6%AE%E0%A7%81%E0%A6%96-%E0%A6%AD%E0%A7%8B%E0%A6%B2%E0%A6%BE-%E0%A6%AF%E0%A6%BE%E0%A7%9F-%E0%A6%A8%E0%A6%BE%E2%80%99-%E0%A6%B6%E0%A7%8B%E0%A6%95%E0%A6%BE%E0%A6%B0%E0%A7%8D%E0%A6%A4-%E0%A6%A8%E0%A6%BE%E0%A6%9C%E0%A7%87%E0%A6%B0%E0%A6%BF%E0%A7%9F%E0%A6%BE%E0%A6%B0-%E0%A6%AA%E0%A7%8D%E0%A6%B0%E0%A6%AF%E0%A7%81%E0%A6%95%E0%A7%8D%E0%A6%A4%E0%A6%BF-%E0%A6%89%E0%A6%A6%E0%A7%8D%E0%A6%AF%E0%A7%8B%E0%A6%95%E0%A7%8D%E0%A6%A4%E0%A6%BE%E0%A6%B0%E0%A6%BE%C2%A0)

**Comment by eggplants** [comment]
Same. See: https://gist.github.com/eggplants/138ce2ee76617023c79089460b296458

**Comment by brandongalbraith** [comment]
Try again. Whatever issue appears to have been transient.

**Comment by pyprism** [comment]
Currently this [solution](https://github.com/pastpages/savepagenow/issues/26#issuecomment-667338453) solves my problem.
