### ISSUE TITLE
Saves a jetpack.js file for an article

### ISSUE THREAD

**Issue by ghost** [palewire/savepagenow#39]
`savepagenow http://thegg.net/interviews/ion-fury-interview-with-voidpoint-game-development-and-ion-furys-past-present-and-future/`

outputs:

`https://web.archive.org/web/20210621000231/https://s0.wp.com/wp-content/js/devicepx-jetpack.js?ver=202125`

https://archive.org/web/ isn't affected: https://web.archive.org/web/*/http://thegg.net/interviews/ion-fury-interview-with-voidpoint-game-development-and-ion-furys-past-present-and-future/

**Comment by palewire** [comment]
Weird. Can you reproduce this?

**Comment by ghost** [comment]
> Weird. Can you reproduce this?

Not for the current 1.2.1 version (Ubuntu 21.10).
