### ISSUE TITLE
submit repository in conda-forge

### ISSUE THREAD

**Issue by rafaelrdealmeida** [palewire/savepagenow#40]
Would it be possible to put the package in conda-forge?

We use conda with a virtual environment and it would be very useful to be able to use savepagenow there

Or is there any instruction on how to use the repository generically in any virtual environment?

cheers

**Comment by palewire** [comment]
How is this done? I don't know anything about conda.

**Comment by corneliusroemer** [comment]
@rafaelrdealmeida you can submit it yourself :) https://conda-forge.org/#add_recipe

https://github.com/conda-forge/staged-recipes
