### ISSUE TITLE
Use HTTPS Scheme To Perform Archival Operation

### ISSUE THREAD

**Issue by brandongalbraith** [palewire/savepagenow#9]
It appears that `http://web.archive.org` [is used to perform archival of a resource](https://github.com/pastpages/savepagenow/blob/master/savepagenow/api.py#L24-L27) instead of `https://web.archive.org`, allowing for the request to be MITMd or similar at the transport layer. Would you accept a PR for this to be modified to use the HTTPS scheme for archival operations?

**Comment by palewire** [comment]
Sure. Though I am not currently making new snapshots. Where do you imagine patching this repo?

**Comment by brandongalbraith** [comment]
I can make the modification to my own fork if your project is no longer being maintained.

**Comment by palewire** [comment]
I'm happy to accept the patch, but FYI the only intense development you can expect here in the future is retiring the back archive to IA
